<?php

namespace wbrowar\guide\helpers;

use Craft;
use craft\helpers\App;
use craft\helpers\Json;
use wbrowar\guide\Guide;
use wbrowar\guide\web\assets\GuideAdminAsset;
use wbrowar\guide\web\assets\GuideDisplayAsset;

class GuideAssetHelper
{
    public static function getHmrUrl(): string
    {
        return App::parseEnv('$VITE_GUIDE_HMR') ? 'http://localhost:3100/' : '';
    }

    /**
     * When in local development mode, register the Vite dev server.
     * Otherwise, register the asset bundles.
     *
     * @return void
     * @throws \yii\base\InvalidConfigException
     */
    public static function registerAssetFiles(string $filename): void
    {
        if (App::parseEnv('$VITE_GUIDE_HMR')) {
            Craft::$app->getView()->registerJsFile(GuideAssetHelper::getHmrUrl() . $filename, ['defer' => true, 'type' => 'module']);
        } else {
            switch ($filename) {
                case 'guide-admin.ts':
                    Craft::$app->getView()->registerAssetBundle(GuideAdminAsset::class);
                    break;
                case 'guide-display.ts':
                    Craft::$app->getView()->registerAssetBundle(GuideDisplayAsset::class);
                    break;
            }
        }
    }

    /**
     * Get paths of all JS and CSS files generated by Vite
     *
     * @param string $filename The name of the Vite entry file, usually 'main.ts'
     * @return array
     */
    public static function getPathsToAssetFiles(string $filename): array
    {
        $assetPaths = [
            'css' => [
                'filename' => '',
                'path' => '',
            ],
            'js' => [
                'filename' => '',
                'path' => '',
            ],
        ];

        $manifestPath = Guide::$plugin->getBasePath() . '/web/assets/dist/.vite/manifest.json';

        if (file_exists($manifestPath)) {
            $manifestJson = file_get_contents($manifestPath);

            if (!empty($manifestJson)) {
                $manifest = Json::decodeIfJson($manifestJson);

                if (!empty($manifest) && $manifest[$filename]) {
                    $path = Craft::$app->getAssetManager()->getPublishedUrl('@wbrowar/guide/web/assets/dist/', true);

                    if (!empty($path)) {
                        if ($manifest[$filename]['css'] ?? false) {
                            $assetPaths['css']['filename'] = substr($manifest[$filename]['css'][0], 7);
                            $assetPaths['css']['path'] = $path . '/' . $manifest[$filename]['css'][0];
                        }
                        if ($manifest[$filename]['file'] ?? false) {
                            $assetPaths['js']['filename'] = substr($manifest[$filename]['file'], 7);
                            $assetPaths['js']['path'] = $path . '/' . $manifest[$filename]['file'];
                        }
                    }
                }
            }
        }

        return $assetPaths;
    }
}